# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08bbe4149233c89550c7aa39147dd80860cf7a4b6bfead060e7547bcc13cd8a23a49e60974927273f3019ee28647f76c69f166c533860821a08ad2b70c914ea7

test:
  secret_key_base: 151ff6ddb91d3dac1129e59874d2cef0e45ce35678b1d27907becf5c1be7967c678a1b9a1d6c6dc8a4f387de06d75f664de52609f6152cc874eb0d34419c6e10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
